apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-list-pvc
  namespace: todolist-grupo-01
  labels:
    app: todo-list
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi