apiVersion: v1
kind: Service
metadata:
 name: cluster-ip-service
 namespace: todolist-grupo-01
spec:
  type: ClusterIP
  selector:
    component: todo-list-app
  ports:
    - port: 80
      targetPort: 5000
