apiVersion: v1
kind: Secret
metadata:
  name: todo-list-secret
  namespace: todolist-grupo-01
type: Opaque
data:
  SESSION_KEY: "clpKVHJRQ3ZKK25oY0dBVElMRFZFeEdXUEM2SEVkaFltYWEvM1FoK21FVT0="
  ADMIN_USER: "YWRtaW4="
  ADMIN_PASSWORD: "YWRtaW4xMjM="
  CLEANUP_TOKEN: "ZDA5N2I5NTVlYzdlNmZhMDVhNDc5MTc1MGQ3ZGEw"
